### PR TITLE
Exporting wallet using NEP-6 format

### LINKED ISSUE #70: Exporting wallet using NEP-6 format
**Summary or problem description**
On issue #59, we're covering a way for creating a wallet using NEP-6. On this issue, we need a way to export it.
**Do you have any solution you want to propose?**
- We should support wallet export, where the account information (including private key, password, address, etc.), should be stored in a specified wallet NEP-6 JSON file.
- Users should choose the path they want the file to be exported to.
- Users should be able to change the password when exporting a wallet, if they want to.

**Additional contextual information**
- Depends on issue #59

[Save()](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/wallet.go#L145-L160)
[JSON()](https://github.com/nspcc-dev/neo-go/blob/b0e8e37b99497ada3c5edd0d7f115f60aeba0aab/pkg/wallet/wallet.go#L172-L181)

### PR DESCRIPTION
**Pull request by meevee98**
Refining file generation using NEP-6 format.
Waiting for #80 and #81 to proceed.

**Related issue**
closes #70

### CODE REVIEW

**Comment by ixje** [comment]
I'm getting really confused as to what I need to review where. I see 3 pr's with nearly identical code? 😕

**Comment by meevee98** [comment]
It's because this branch was created from the one in #80. The changes in GitHub show all the code from that plus the changes made here.

This one depends on the code from #80 so could you review that first?

**Comment by meevee98** [comment]
@ixje can you take a look?

**Comment by ixje** [comment]
What should I look at, only the the `to_json()`? 
Also, can you please do regular pushes instead of forced pushes. Every time you force push I loose all history and everything is marked a new changes.

**Comment by meevee98** [comment]
> What should I look at, only the the `to_json()`?

Yes, this pull request is for refining `to_json` to follow NEP6.

> Also, can you please do regular pushes instead of forced pushes. Every time you force push I loose all history and everything is marked a new changes.

Sure, no prob. These forced pushes are because of rebases with conflicts. I won't do it again.

**Pull request merged**
